QBCore.Functions.CreateUseableItem('wine24', function()
    local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('wine24')
    Wait(500)
    Player.Functions.AddItem('wine', 24)
end)

QBCore.Functions.CreateUseableItem('wine12', function()
    local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('wine12')
    Wait(500)
    Player.Functions.AddItem('wine', 12)
end)

QBCore.Functions.CreateUseableItem('wine6', function()
    local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('wine6')
    Wait(500)
    Player.Functions.AddItem('wine', 6)
end)

QBCore.Functions.CreateUseableItem('grapejuice24', function()
    local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('grapejuice24')
    Wait(500)
    Player.Functions.AddItem('grapejuice', 24)
end)

QBCore.Functions.CreateUseableItem('grapejuice12', function()
    local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('grapejuice12')
    Wait(500)
    Player.Functions.AddItem('grapejuice', 12)
end)

QBCore.Functions.CreateUseableItem('grapejuice6', function()
	local Player = QBCore.Functions.GetPlayer(source)
    Player.Functions.RemoveItem('grapejuice6')
    Wait(500)
    Player.Functions.AddItem('grapejuice', 6)
end)